presubmits:
- always_run: true
  context: op1st/prow/pre-commit
  decorate: true
  name: pre-commit
  skip_report: false
  spec:
    containers:
    - command:
      - pre-commit
      - run
      - --all-files
      image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
- always_run: true
  context: op1st/prow/mypy
  decorate: true
  name: thoth-mypy-py38
  skip_report: false
  spec:
    containers:
    - command:
      - /usr/local/bin/mypy
      - .
      image: quay.io/thoth-station/thoth-pytest-ubi8-py38:v0.15.0
