- project:
    check:
      jobs:
        - linters
    gate:
      queue: thoth-station/core
      jobs:
        - linters
    kebechet-auto-gate:
      queue: thoth-station/core
      jobs:
        - linters
