# Inspection Run Workflow Template
#
# This workflow submits an inspection Job which creates `n` pod replicas and runs them in a sequence.
#
# successCondition: `n` pods have finished successfully and are present in the cluster
# failureCondition: there are more failures than is allowed (a constant to account for potential flakes)
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: inspection-run-with-cpu-template
  annotations:
    thoth-station.ninja/template-version: 0.5.3
spec:
  entrypoint: main

  templates:
  - name: main
    inputs:
      parameters:
      # Required
      - name: inspection-id
      - name: batch-name
      - name: batch-size
      # Hardware parameters
      - name: cpu-family
      - name: cpu-model
      - name: physical-cpus
      - name: processor
      # Defaults
      - name: affinity
        value: "false"
      - name: cpu
        value: "750m"
      - name: memory
        value: "1Gi"
      - name: registry
        value: docker-registry.default.svc:5000
      - name: thoth-infra-namespace
        value: "{{workflow.namespace}}"
    steps:
    - - name: job
        arguments: &arguments
          parameters:
          - name: inspection-id
            value: "{{inputs.parameters.inspection-id}}"
          - name: batch-name
            value: "{{inputs.parameters.batch-name}}"
          - name: batch-size
            value: "{{inputs.parameters.batch-size}}"
          - name: cpu
            value: "{{inputs.parameters.cpu}}"
          - name: cpu-family
            value: "{{inputs.parameters.cpu-family}}"
          - name: cpu-model
            value: "{{inputs.parameters.cpu-model}}"
          - name: memory
            value: "{{inputs.parameters.memory}}"
          - name: physical-cpus
            value: "{{inputs.parameters.physical-cpus}}"
          - name: processor
            value: "{{inputs.parameters.processor}}"
          - name: registry
            value: "{{inputs.parameters.registry}}"
          - name: thoth-infra-namespace
            value: "{{inputs.parameters.thoth-infra-namespace}}"
        template: create-job
        when: "{{inputs.parameters.affinity}} == false"

    - - name: job-with-affinity
        arguments: *arguments
        template: create-job-with-affinity
        when: "{{inputs.parameters.affinity}} == true"

    - - name: inspection
        arguments:
          parameters:
          - name: batch-name
            value: "{{inputs.parameters.batch-name}}"
          - name: batch-size
            value: "{{inputs.parameters.batch-size}}"
        template: await-inspection
        continueOn:
          error: true
          failed: true

    - - name: on-failure
        arguments:
          parameters:
          - name: batch-name
            value: "{{inputs.parameters.batch-name}}"
        template: on-failure
        when: "{{steps.inspection.status}} != Succeeded"


  # TODO: Run each performance indicator directly from the Workflow
  # instead of submitting a job and monitoring it
  - name: create-job
    inputs:
      parameters:
      - name: inspection-id
      - name: batch-name
      - name: batch-size
      - name: cpu
      - name: memory
      - name: registry
      - name: thoth-infra-namespace
    resource:
      action: create
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: "{{inputs.parameters.batch-name}}"
          labels:
              app: amun
              component: amun-inspection-job
              amun/template: amun-inspection-job
              amun/inspection-id: "{{inputs.parameters.inspection-id}}"
              amun/task: inspection
              mark: cleanup
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            name: "{{workflow.name}}"
            uid: "{{workflow.uid}}"
        spec:
          backoffLimit: 0
          completions: {{inputs.parameters.batch-size}}
          parallelism: 1
          template:
            metadata:
              name: "{{inputs.parameters.batch-name}}-job"
              labels:
                app: amun
                component: amun-inspection-job
                amun/inspection-id: "{{inputs.parameters.inspection-id}}"
                amun/batch-size: "{{inputs.parameters.batch-size}}"
                amun/batch-name: "{{inputs.parameters.batch-name}}"
                amun/task: inspection
            spec:
              automountServiceAccountToken: false
              restartPolicy: Never
              containers:
              - name: inspect
                env: []
                image: "{{inputs.parameters.inspection-id}}:latest"
                livenessProbe:
                  failureThreshold: 1
                  initialDelaySeconds: 7200
                  periodSeconds: 10
                  tcpSocket:
                    port: 80
                resources:
                  limits:
                    memory: "{{inputs.parameters.memory}}"
                    cpu: "{{inputs.parameters.cpu}}"
                  requests:
                    memory: "{{inputs.parameters.memory}}"
                    cpu: "{{inputs.parameters.cpu}}"
                volumeMounts:
                  - mountPath: /home/amun/hwinfo
                    name: hw-info-volume
              initContainers:
              - name: inspect-hwinfo
                image: |-
                  {{inputs.parameters.registry}}/{{inputs.parameters.thoth-infra-namespace}}/inspect-hwinfo
                volumeMounts:
                  - mountPath: /home/amun/hwinfo
                    name: hw-info-volume
              volumes:
              - name: hw-info-volume
                emptyDir: {}

  - name: create-job-with-affinity
    inputs:
      parameters:
      - name: inspection-id
      - name: batch-name
      - name: batch-size
      - name: cpu
      - name: cpu-family
      - name: cpu-model
      - name: physical-cpus
      - name: processor
      - name: memory
      - name: registry
      - name: thoth-infra-namespace
    resource:
      action: create
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: "{{inputs.parameters.batch-name}}"
          labels:
              app: amun
              component: amun-inspection-job
              amun/template: amun-inspection-job
              amun/inspection-id: "{{inputs.parameters.inspection-id}}"
              amun/task: inspection
              mark: cleanup
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            name: "{{workflow.name}}"
            uid: "{{workflow.uid}}"
        spec:
          completions: {{inputs.parameters.batch-size}}
          parallelism: 1
          template:
            metadata:
              name: "{{inputs.parameters.batch-name}}-job"
              labels:
                app: amun
                component: amun-inspection-job
                amun/inspection-id: "{{inputs.parameters.inspection-id}}"
                amun/batch-size: "{{inputs.parameters.batch-size}}"
                amun/batch-name: "{{inputs.parameters.batch-name}}"
                amun/task: inspection
            spec:
              automountServiceAccountToken: false
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: CPU_FAMILY
                            operator: In
                            values:
                              - "{{inputs.parameters.cpu-family}}"
                          - key: CPU_MODEL
                            operator: In
                            values:
                              - "{{inputs.parameters.cpu-model}}"
                          - key: PHYSICAL_CPUS
                            operator: In
                            values:
                              - "{{inputs.parameters.physical-cpus}}"
                          - key: processor
                            operator: In
                            values:
                              - "{{inputs.parameters.processor}}"
              restartPolicy: Never
              containers:
              - name: inspect
                env: []
                image: "{{inputs.parameters.inspection-id}}:latest"
                livenessProbe:
                  failureThreshold: 1
                  initialDelaySeconds: 7200
                  periodSeconds: 10
                  tcpSocket:
                    port: 80
                resources:
                  limits:
                    memory: "{{inputs.parameters.memory}}"
                    cpu: "{{inputs.parameters.cpu}}"
                  requests:
                    memory: "{{inputs.parameters.memory}}"
                    cpu: "{{inputs.parameters.cpu}}"
                volumeMounts:
                  - mountPath: /home/amun/hwinfo
                    name: hw-info-volume
              initContainers:
              - name: inspect-hwinfo
                image: |-
                  {{inputs.parameters.registry}}/{{inputs.parameters.thoth-infra-namespace}}/inspect-hwinfo
                volumeMounts:
                  - mountPath: /home/amun/hwinfo
                    name: hw-info-volume
              volumes:
              - name: hw-info-volume
                emptyDir: {}

  - name: await-inspection
    inputs:
      parameters:
      - name: batch-name
      - name: batch-size
    resource:
      action: get
      successCondition: status.succeeded == {{inputs.parameters.batch-size}}
      failureCondition: status.failed > 0
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: "{{inputs.parameters.batch-name}}"

  # Suspend the inspection Job
  - name: on-failure
    inputs:
      parameters:
      - name: batch-name
    resource:
      action: patch
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: "{{inputs.parameters.batch-name}}"
        spec:
          parallelism: 0
