kind: Template
apiVersion: v1
metadata:
  name: amun-inspection-job-with-cpu
  annotations:
    description: Amun - Execution engine for Thoth
    openshift.io/display-name: Amun API
    version: 0.0.1
    tags: poc,amun,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run Amun's inspection job on OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: amun-inspection-job-with-cpu
    app: amun
    component: amun-inspection-job

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "${AMUN_INSPECTION_ID}"
      labels:
        app: amun
        component: amun-inspection-job
        amun_template: amun-inspection-job-with-cpu
        operator: graph-sync
        task: inspection
        mark: cleanup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: amun
            component: amun-inspection-job
            amun_template: amun-inspection-job-with-cpu
            mark: cleanup
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          containers:
            - name: inspect
              env: []
              image: '${AMUN_INSPECTION_ID}:latest'
              livenessProbe:
                failureThreshold: 1
                initialDelaySeconds: 3600
                periodSeconds: 10
                tcpSocket:
                  port: 80
              resources:
                limits:
                  cpu: ${AMUN_CPU}
                  memory: ${AMUN_MEMORY}
                requests:
                  cpu: ${AMUN_CPU}
                  memory: ${AMUN_MEMORY}
              volumeMounts:
                - mountPath: /home/amun/hwinfo
                  name: hw-info-volume
          initContainers:
            - name: inspect-hwinfo
              image: "${THOTH_REGISTRY}/${THOTH_INFRA_NAMESPACE}/inspect-hwinfo"
              volumeMounts:
                - mountPath: /home/amun/hwinfo
                  name: hw-info-volume
          volumes:
            - name: hw-info-volume
              emptyDir: {}
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames: [inspect]
            from:
              kind: ImageStreamTag
              name: '${AMUN_INSPECTION_ID}:latest'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: CPU_FAMILY
                    operator: In
                    values:
                      - ${CPU_FAMILY}
                  - key: CPU_MODEL
                    operator: In
                    values:
                      - ${CPU_MODEL}
                  - key: PHYSICAL_CPUS
                    operator: In
                    values:
                      - ${PHYSICAL_CPUS}
                  - key: processor
                    operator: In
                    values:
                      - ${PROCESSOR}

parameters:
  - name: THOTH_REGISTRY
    description: Registry server from where Image is to be pulled
    displayName: Registry
    required: true
    default: docker-registry.default.svc:5000

  - name: THOTH_INFRA_NAMESPACE
    description: Project where ImageStream is present
    displayName: ImageStream Project
    required: true

  - name: AMUN_INSPECTION_ID
    description: Id of inspection that is run.
    displayName: Inspection id
    required: true

  - name: AMUN_CPU
    description: CPU cores requested for build
    displayName: Build CPU
    default: 750m

  - name: AMUN_MEMORY
    description: Memory requested for build
    displayName: Build Memory
    default: 256Mi

  - name: CPU_FAMILY
    description: Family number of CPU.
    displayName: CPU Family
    required: true

  - name: CPU_MODEL
    description: Modelnumber of CPU.
    displayName: CPU model
    required: true

  - name: PHYSICAL_CPUS
    description: Number of physical CPUs.
    displayName: Physical CPUS
    required: true

  - name: PROCESSOR
    description: Name of processor.
    displayName: Processor name
    required: true
