apiVersion: v1
kind: Template
metadata:
  name: amun-inspection-imagestream
  annotations:
    description: >
      This is Thoth Adviser ImageStream, this template is meant to be used by Jenkins, but could also
      be used by humans
    openshift.io/display-name: Dynamically generated ImageStream for dynamic inspection builds.
    version: 0.5.1
    tags: amun,thoth,ai-stacks,adviser
    template.openshift.io/documentation-url: https://github.com/Thoth-Station
    template.openshift.io/long-description: >
      This is Thoth Adviser ImageStream, this template is meant to be used by Jenkins, but could also
      be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.5.1
  labels:
    app: amun
    component: amun-inspection-imagestream
    template: amun-inspection-imagestream

objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.5.1
      labels:
        app: amun
        component: amun-inspection-imagestream
        mark: cleanup
      name: ${AMUN_INSPECTION_ID}
    spec:
      name: latest
      lookupPolicy:
        local: true

parameters:
  - name: AMUN_INSPECTION_ID
    description: Id of inspection that is run.
    displayName: Inspection id
    required: true
