apiVersion: v1
kind: Template
metadata:
  name: amun-secrets
  annotations:
    description: This is Amun Secrets definition.
    openshift.io/display-name: Amun Secrets
    version: 0.0.1
    tags: poc,amun,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines secrets required to deploy Amun.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    app: amun
    template: amun-secrets
    component: secrets

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: amun
      labels:
        app: amun
        component: secrets
    stringData:
      app-secret-key: ${AMUN_API_APP_SECRET_KEY}
      sentry-dsn: ${SENTRY_DSN}

parameters:
  - description: Secret key for flask application to have secured session connections.
    displayName: App secret key
    required: true
    name: AMUN_API_APP_SECRET_KEY

  - displayName: SENTRY_DSN
    description: A DSN to a Sentry instance to log to.
    name: SENTRY_DSN
    required: false
